#version 400

in vec3 fragPos;
in vec3 normal;
in vec2 texCoords;
in vec3 vertexColour;
in vec3 objPos;

uniform vec3 lightPos; 
uniform vec3 lightColour;    
uniform vec3 camPos;
uniform sampler2D diffuse;
uniform bool hasTexture;

uniform sampler2D textureNoise; // Grayscale noise texture
uniform float deadProgression;   // 0.0 (alive) to 1.0 (dead)

out vec4 fragmentColour;

// ADS Constants
float ambientStrength = 0.4;
float specularStrength = 0.8;
float shininess = 32.0;   


//i kept my ADS calculation that i have already done
//and the rest was generated by claude.ai/gemini
//i dont know wether i need to show the entire chat
//but its mainly just a lot of back and fourth with
//the resulting tank being too black or orange and asking 
//it to fix it

//original prompt to gemini "i want my dead tank shader to make the tank be black with orange ember highlights""

//after about 20 back and fourth messages it wasnt working so i asked claude : 
//"Im trying to make a shader for my dead tank that is black/dark grey with ember 
//lines going through it i am using perlin noise but the tank is either completly black or 
//completly yellow when. This is my current frag shader the vert whould be fine and have no reason to change"

//it then generate from line 56 down

void main()
{
    //ADS
    vec3 texColour = texture(diffuse, texCoords).rgb;
    vec3 ambient = ambientStrength * lightColour;
    vec3 lightDir = normalize(lightPos - fragPos);
    float diff = max(dot(normal, lightDir), 0.0);
    vec3 diffuse = diff * lightColour;
    vec3 viewDir = normalize(camPos - fragPos);
    vec3 reflectDir = reflect(-lightDir, normal);
    float spec = pow(max(dot(viewDir, reflectDir), 0.0), shininess);
    vec3 specular = specularStrength * spec * lightColour;
    vec3 lighting = (ambient + diffuse + specular);

    vec3 baseColour;
    if(hasTexture)
        baseColour = lighting * texColour;
    else
        baseColour = lighting * vertexColour;




    vec3 charcoal = vec3(0.08, 0.08, 0.08);
    vec3 deadSurface = lighting * charcoal;

    vec3 surface = mix(baseColour, deadSurface, deadProgression);

    vec2 noiseUV = objPos.xz * 0.3;
    float n1 = texture(textureNoise, noiseUV).r;
    vec2 warpedUV = objPos.xy * 0.4 + vec2(n1 * 0.9, n1 * 0.6);
    float n2 = texture(textureNoise, warpedUV).r;
    float noise = n1 * 0.5 + n2 * 0.5;

    float band = abs(fract(noise * 1.5) - 0.5) * 2.0;

    float veins = 1.0 - smoothstep(0.0, 0.08, band);

    vec3 emberColor = vec3(1.0, 0.25, 0.0);

    vec3 glow = emberColor * veins * 3.0 * deadProgression;
    vec3 result = clamp(surface + glow, 0.0, 1.0);

    fragmentColour = vec4(result, 1.0);
}